// Execution entry point for the 3D Face Reconstruction Pipeline.
// This binary handles command-line argument parsing, loads the statistical
// Basel Face Model, and orchestrates the facial alignment optimization loops.

#include "face_recon/bfm_model.h"
#include "face_recon/dense_fitting.h"
#include "face_recon/fitting.h"
#include "face_recon/image_fitting.h"
#include "face_recon/mesh_export.h"
#include "face_recon/photometric_fitting.h"
#include "face_recon/rasterizer.h"
#include "face_recon/silhouette_fitting.h"
#include "face_recon/texture_fitting.h"
#include "face_reconstruction/landmarks.hpp"

#include <CLI/CLI.hpp>
#include <filesystem>
#include <iostream>
#include <optional>
#include <string>

int main(int argc, char* argv[]) {
  // Instantiate the App parser framework.
  CLI::App app{"TUM 3D Scanning and Motion Capture: 3D Face Reconstruction Optimization Loop Pipeline"};

  // Set up runtime parameters with safe defaults.
  std::string model_path = "assets/models/model2019_face12.h5";
  std::string output_dir = "outputs/results";
  std::string correspondence_path = "data/bfm_mediapipe_correspondence.csv";
  std::optional<std::string> output_name;
  std::optional<std::string> landmark_path;
  std::optional<std::string> image_path;
  std::optional<std::string> silhouette_mask_path;
  std::optional<std::string> occluder_mask_path;
  bool check_bfm = false;
  bool verbose_optimization = false;
  bool save_diagnostics = false;
  face_recon::FittingOptions fitting_options;
  face_recon::PhotometricOptions photometric_options;
  face_recon::SilhouetteFittingOptions silhouette_options;
  face_recon::TextureFittingOptions texture_options;
  face_recon::DenseFittingOptions dense_options;
  bool disable_dense_fitting = false;
  bool disable_dense_pose = false;
  bool disable_silhouette_fitting = false;
  bool disable_landmark_visibility_filter = false;
  bool disable_pose_landmark_filter = false;

  // Define the available CLI flags and options.
  app.add_option("-m,--model", model_path, "Path to the Basel Face Model HDF5 asset container")->check(CLI::ExistingFile);
  app.add_option("-o,--output", output_dir, "Directory to save the reconstruction results");
  app.add_option("--output-name", output_name,
                 "Use compact filenames for a dedicated per-image output directory");
  app.add_flag("-c,--check-bfm", check_bfm, "Run structural loading checks and output comprehensive database dumps");
  app.add_option("-l,--landmarks", landmark_path,
                 "MediaPipe landmark CSV to fit; generated by the Python landmark detector")
      ->check(CLI::ExistingFile);
  app.add_option("-i,--image", image_path,
                 "Original face image; enables photo colors and reprojection overlay")
      ->check(CLI::ExistingFile);
  app.add_option("--silhouette-mask", silhouette_mask_path,
                 "Binary target face mask for silhouette-aware geometry fitting")
      ->check(CLI::ExistingFile);
  app.add_option("--occluder-mask", occluder_mask_path,
                 "Binary mask of external occluders (hair/hands/clothes); "
                 "excluded from appearance sampling and silhouette matching")
      ->check(CLI::ExistingFile);
  app.add_option("--correspondences", correspondence_path,
                 "MediaPipe-to-BFM correspondence CSV")
      ->check(CLI::ExistingFile);
  app.add_option("--shape-components", fitting_options.num_shape_coefficients,
                 "Number of BFM identity coefficients to optimize");
  app.add_option("--expression-components", fitting_options.num_expression_coefficients,
                 "Number of BFM expression coefficients to optimize");
  app.add_option("--shape-regularization", fitting_options.shape_regularization,
                 "Weight of the identity PCA prior");
  app.add_option("--expression-regularization",
                 fitting_options.expression_regularization,
                 "Weight of the expression PCA prior");
  app.add_option("--focal-regularization",
                 fitting_options.focal_regularization,
                 "Weight keeping normalized focal length near a typical portrait camera");
  app.add_option("--landmark-weight", fitting_options.landmark_weight,
                 "Weight of the sparse landmark reprojection term");
  app.add_option("--outlier-threshold", fitting_options.outlier_threshold,
                 "Maximum normalized residual before rejecting a semantic landmark");
  app.add_flag("--no-landmark-visibility-filter",
               disable_landmark_visibility_filter,
               "Keep self-occluded semantic landmarks in the joint fit");
  app.add_option("--landmark-depth-tolerance",
                 fitting_options.landmark_visibility_depth_tolerance,
                 "Inverse-depth Z-buffer tolerance for landmark visibility");
  app.add_flag("--no-pose-landmark-filter", disable_pose_landmark_filter,
               "Keep far-side semantic landmarks at strong yaw angles");
  app.add_option("--pose-yaw-threshold", fitting_options.pose_yaw_threshold,
                 "Absolute yaw in radians for far-side landmark rejection");
  app.add_option("--landmark-mask-tolerance",
                 fitting_options.landmark_mask_tolerance,
                 "Allowed normalized distance outside the face-skin mask");
  app.add_flag("-v,--verbose-optimization", verbose_optimization,
               "Print Ceres iteration progress");
  app.add_flag("--diagnostics", save_diagnostics,
               "Save detailed fitting, rasterization, and appearance diagnostics");
  app.add_option("--albedo-components",
                 photometric_options.num_albedo_coefficients,
                 "Number of normalized BFM albedo coefficients");
  app.add_option("--photometric-stride", photometric_options.pixel_stride,
                 "Use every Nth visible pixel during appearance fitting");
  app.add_option("--photometric-mask-erosion",
                 photometric_options.mask_erosion,
                 "Erode the visible face mask by this many pixels");
  app.add_option("--albedo-regularization",
                 photometric_options.albedo_regularization,
                 "Weight of the normalized albedo PCA prior");
  app.add_option("--photometric-huber-delta",
                 photometric_options.huber_delta,
                 "Huber threshold for RGB residuals in [0,1]");
  app.add_flag("--no-silhouette-fitting", disable_silhouette_fitting,
               "Skip mask-driven identity refinement");
  app.add_option("--silhouette-resolution", silhouette_options.resolution,
                 "Maximum mask dimension used for silhouette fitting");
  app.add_option("--silhouette-iterations",
                 silhouette_options.outer_iterations,
                 "View-dependent silhouette rematching iterations");
  app.add_option("--silhouette-weight",
                 silhouette_options.silhouette_weight,
                 "Weight of bidirectional silhouette correspondences");
  app.add_option("--silhouette-semantic-weight",
                 silhouette_options.semantic_weight,
                 "Weight preserving the 40 semantic landmarks");
  app.add_option("--silhouette-shape-regularization",
                 silhouette_options.shape_regularization,
                 "BFM identity prior weight during silhouette fitting");
  app.add_option("--texture-stride", texture_options.pixel_stride,
                 "Use every Nth visible pixel during dense RGB fitting");
  app.add_option("--texture-mask-erosion", texture_options.mask_erosion,
                 "Erode the dense RGB fitting mask by this many pixels");
  app.add_option("--texture-prior", texture_options.prior_weight,
                 "Weight retaining initialized vertex RGB values");
  app.add_option("--texture-smoothness", texture_options.smoothness_weight,
                 "Mesh-edge smoothness weight for fitted vertex RGB values");
  app.add_flag("--no-dense-fitting", disable_dense_fitting,
               "Skip the dense photometric expression/pose refinement");
  app.add_option("--dense-expression-components",
                 dense_options.num_expression_coefficients,
                 "Expression coefficients driven by the dense photometric term");
  app.add_option("--dense-stride", dense_options.pixel_stride,
                 "Use every Nth visible pixel during dense photometric fitting");
  app.add_option("--dense-outer-iterations", dense_options.outer_iterations,
                 "Re-rasterization (visibility refresh) iterations");
  app.add_option("--dense-landmark-weight", dense_options.landmark_weight,
                 "Weight of the semantic landmark anchors in the dense problem");
  app.add_option("--dense-expression-regularization",
                 dense_options.expression_regularization,
                 "Expression PCA prior weight during dense fitting");
  app.add_option("--dense-huber-delta", dense_options.huber_delta,
                 "Huber threshold for dense RGB residuals in [0,1]");
  app.add_flag("--dense-no-pose", disable_dense_pose,
               "Keep rotation/translation fixed during dense fitting");

  // Execute the parse routine safely
  try {
    app.parse(argc, argv);
  } catch (const CLI::ParseError& e) {
    // Print the correct usage information and exit with the corresponding exit code on wrong input.
    return app.exit(e);
  }

  if (fitting_options.num_shape_coefficients <= 0 ||
      fitting_options.num_expression_coefficients <= 0) {
    std::cerr << "[ERROR] Component counts must be positive.\n";
    return 1;
  }
  if (fitting_options.landmark_weight <= 0.0 ||
      fitting_options.shape_regularization < 0.0 ||
      fitting_options.expression_regularization < 0.0 ||
      fitting_options.focal_regularization < 0.0 ||
      fitting_options.outlier_threshold <= 0.0 ||
      fitting_options.landmark_visibility_depth_tolerance <= 0.0f ||
      fitting_options.pose_yaw_threshold <= 0.0 ||
      fitting_options.landmark_mask_tolerance < 0.0) {
    std::cerr << "[ERROR] Fitting weights and outlier threshold must be "
                 "valid positive values; regularization may be zero.\n";
    return 1;
  }
  if (silhouette_options.resolution <= 0 ||
      silhouette_options.outer_iterations <= 0 ||
      silhouette_options.solver_iterations <= 0 ||
      silhouette_options.sample_stride <= 0 ||
      silhouette_options.semantic_weight <= 0.0 ||
      silhouette_options.silhouette_weight <= 0.0 ||
      silhouette_options.shape_regularization < 0.0 ||
      silhouette_options.huber_delta < 0.0 ||
      silhouette_options.maximum_correspondence_distance <= 0.0 ||
      silhouette_options.semantic_degradation_limit < 1.0) {
    std::cerr << "[ERROR] Silhouette-fitting options are invalid.\n";
    return 1;
  }
  if (photometric_options.num_albedo_coefficients <= 0 ||
      photometric_options.pixel_stride <= 0 ||
      photometric_options.mask_erosion < 0 ||
      photometric_options.albedo_regularization < 0.0 ||
      photometric_options.huber_delta < 0.0) {
    std::cerr << "[ERROR] Photometric options must be non-negative, and "
                 "component count/stride must be positive.\n";
    return 1;
  }
  if (texture_options.pixel_stride <= 0 ||
      texture_options.mask_erosion < 0 ||
      texture_options.prior_weight < 0.0 ||
      texture_options.smoothness_weight < 0.0) {
    std::cerr << "[ERROR] Dense texture options must be non-negative, and "
                 "pixel stride must be positive.\n";
    return 1;
  }
  if (dense_options.num_expression_coefficients <= 0 ||
      dense_options.pixel_stride <= 0 ||
      dense_options.mask_erosion < 0 ||
      dense_options.outer_iterations <= 0 ||
      dense_options.solver_iterations <= 0 ||
      dense_options.landmark_weight < 0.0 ||
      dense_options.expression_regularization < 0.0 ||
      dense_options.huber_delta < 0.0) {
    std::cerr << "[ERROR] Dense photometric fitting options are invalid.\n";
    return 1;
  }
  photometric_options.save_diagnostics = save_diagnostics;
  fitting_options.filter_occluded_landmarks =
      !disable_landmark_visibility_filter;
  fitting_options.filter_landmarks_by_pose = !disable_pose_landmark_filter;
  silhouette_options.enabled = !disable_silhouette_fitting;
  silhouette_options.save_diagnostics = save_diagnostics;
  texture_options.save_diagnostics = save_diagnostics;
  dense_options.enabled = !disable_dense_fitting;
  dense_options.optimize_pose = !disable_dense_pose;
  dense_options.save_diagnostics = save_diagnostics;
  dense_options.verbose = verbose_optimization;
  if (occluder_mask_path.has_value()) {
    photometric_options.occluder_mask_path = *occluder_mask_path;
    texture_options.occluder_mask_path = *occluder_mask_path;
    silhouette_options.occluder_mask_path = *occluder_mask_path;
    dense_options.occluder_mask_path = *occluder_mask_path;
  }

  // Run the core execution pipeline.
  std::cout << "[INFO] Initializing Face Reconstruction Pipeline...\n";
  face_recon::BfmModel model;
  if (!model.LoadFromH5(model_path)) {
    std::cerr << "[ERROR] Failed to configure internal face model architecture from path: " << model_path << "\n";
    return 1;
  }

  // Ensure the output directory exists
  std::filesystem::create_directories(output_dir);

  // Orchestrate pipeline behavior based on runtime flags.
  if (check_bfm) {
    std::cout << "[INFO] Check BFM requested. Exporting validation logs and summaries...\n";
    
    // Output metrics to verify structural integrity.
    model.PrintModelSummary();

    // Generate static 3D face representations.
    model.SaveMeanMeshToPly(output_dir + "/bfm_mean_face.ply", false);
    model.SaveMeanMeshToPly(output_dir + "/bfm_mean_face_with_landmarks.ply", true);
    model.SaveLandmarksToTxt(output_dir + "/bfm_landmarks.txt");
  }

  if (landmark_path.has_value()) {
    fitting_options.verbose = verbose_optimization;
    fitting_options.landmark_mask_path =
        silhouette_mask_path.has_value() ? *silhouette_mask_path : "";
    std::cout << "[INFO] Loading sparse landmark observations...\n";
    const auto landmarks =
        face_reconstruction::load_landmarks_csv(*landmark_path);
    const auto correspondences =
        face_reconstruction::load_bfm_mediapipe_correspondences(correspondence_path);

    std::cout << "[INFO] Fitting camera, identity, and expression parameters...\n";
    face_recon::FittingResult result =
        face_recon::FitBfmToLandmarks(model, landmarks, correspondences,
                                      fitting_options);
    std::cout << result.solver_summary << "\n";
    std::cout << "[RESULT] Landmark RMSE: " << result.initial_rmse
              << " -> " << result.final_rmse << " (normalized image units)\n";

    const bool compact_output = output_name.has_value();
    const std::string stem = compact_output
                                 ? *output_name
                                 : std::filesystem::path(*landmark_path).stem().string();
    const std::filesystem::path mesh_path =
        std::filesystem::path(output_dir) /
        (compact_output ? stem + ".off" : stem + "_fitted.off");
    const std::filesystem::path colored_mesh_path =
        std::filesystem::path(output_dir) /
        (compact_output ? stem + ".ply" : stem + "_fitted.ply");
    const std::filesystem::path aligned_mesh_path =
        std::filesystem::path(output_dir) /
        (compact_output ? stem + "_aligned.ply" : stem + "_fitted_aligned.ply");
    const std::filesystem::path report_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "fitting.txt" : stem + "_fitting.txt");
    const std::filesystem::path reprojection_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "reprojections.csv" : stem + "_reprojections.csv");
    const std::filesystem::path overlay_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "overlay.png" : stem + "_fitting_overlay.png");
    const std::filesystem::path raster_depth_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "raster_depth.png" : stem + "_raster_depth.png");
    const std::filesystem::path visibility_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "visibility.png" : stem + "_visibility.png");
    const std::filesystem::path surface_overlay_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "bfm_surface_overlay.png"
                        : stem + "_bfm_surface_overlay.png");
    const std::filesystem::path intrinsic_albedo_mesh_path =
        std::filesystem::path(output_dir) /
        (compact_output ? stem + "_albedo.ply"
                        : stem + "_fitted_albedo.ply");
    const std::filesystem::path photometric_report_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "photometric.txt"
                        : stem + "_photometric.txt");
    const std::filesystem::path texture_report_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "texture_fitting.txt"
                        : stem + "_texture_fitting.txt");
    const std::filesystem::path silhouette_report_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "silhouette_fitting.txt"
                        : stem + "_silhouette_fitting.txt");
    const std::filesystem::path dense_report_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "dense_fitting.txt"
                        : stem + "_dense_fitting.txt");

    if (!result.usable) {
      std::cerr << "[ERROR] Ceres did not produce a usable fitting result.\n";
      return 1;
    }
    if (silhouette_options.enabled) {
      if (!silhouette_mask_path.has_value()) {
        std::cerr << "[ERROR] Silhouette fitting is enabled but no "
                     "--silhouette-mask was provided.\n";
        return 1;
      }
      std::cout << "[INFO] Refining identity from the view-dependent "
                   "face silhouette...\n";
      const face_recon::SilhouetteFittingResult silhouette_result =
          face_recon::RefineGeometryFromSilhouette(
              *silhouette_mask_path, model, result, silhouette_options,
              output_dir);
      if (!face_recon::SaveSilhouetteFittingReport(
              silhouette_result, silhouette_report_path.string())) {
        std::cerr << "[ERROR] Could not save silhouette-fitting report.\n";
        return 1;
      }
      if (silhouette_result.usable) {
        face_recon::ApplySilhouetteResult(silhouette_result, &result);
        std::cout << "[RESULT] Silhouette Chamfer: "
                  << silhouette_result.initial.silhouette_chamfer << " -> "
                  << silhouette_result.final.silhouette_chamfer
                  << ", IoU: " << silhouette_result.initial.silhouette_iou
                  << " -> " << silhouette_result.final.silhouette_iou
                  << "\n";
      } else {
        std::cerr << "[WARN] Silhouette refinement made no safe improvement; "
                     "keeping the semantic-only geometry.\n";
      }
    }
    Eigen::VectorXd fitted_colors;
    const Eigen::VectorXd* fitted_colors_pointer = nullptr;
    std::optional<face_recon::RasterizationResult> rasterization;
    std::optional<face_recon::PhotometricResult> photometric_result;
    if (image_path.has_value()) {
      const Eigen::Vector2i image_size =
          face_recon::ReadImageSize(*image_path);
      rasterization = face_recon::RasterizeMesh(
          result.vertices, model.triangles(), result.camera,
          image_size.x(), image_size.y());
      const Eigen::VectorXd camera_normals = face_recon::ApplyCameraRotation(
          face_recon::ComputeVertexNormals(result.vertices, model.triangles()),
          result.camera);
      if (!face_recon::SaveBfmSurfaceOverlay(
              *image_path, model.triangles(), camera_normals, *rasterization,
              surface_overlay_path.string())) {
        return 1;
      }
      std::cout << "[INFO] Fitting BFM albedo and first-order SH illumination...\n";
      photometric_result = face_recon::FitPhotometricAppearance(
          *image_path, model, result.vertices, result.camera, *rasterization,
          photometric_options, output_dir);
      if (!photometric_result->usable) {
        std::cerr << "[WARN] Intrinsic albedo/illumination fitting did not "
                     "improve RGB error; dense texture fitting will still "
                     "optimize the primary visual result.\n";
      }
      if (dense_options.enabled) {
        std::cout << "[INFO] Refining expression and pose against the dense "
                     "photometric term...\n";
        const face_recon::DenseFittingResult dense_result =
            face_recon::RefineExpressionDense(
                *image_path, model, result, *photometric_result,
                dense_options, output_dir);
        std::cout << "[RESULT] Dense photometric RMSE: "
                  << dense_result.initial_photometric_rmse << " -> "
                  << dense_result.final_photometric_rmse
                  << ", landmark RMSE: "
                  << dense_result.initial_landmark_rmse << " -> "
                  << dense_result.final_landmark_rmse << "\n";
        if (save_diagnostics &&
            !face_recon::SaveDenseFittingReport(
                dense_result, dense_report_path.string())) {
          std::cerr << "[ERROR] Could not save dense-fitting report.\n";
          return 1;
        }
        if (dense_result.usable) {
          result.camera = dense_result.camera;
          result.expression_coefficients =
              dense_result.expression_coefficients;
          result.vertices = dense_result.vertices;
          // Downstream appearance and texture fitting must see the refined
          // geometry, so refresh the pixel-to-surface mapping and re-separate
          // albedo from illumination once.
          rasterization = face_recon::RasterizeMesh(
              result.vertices, model.triangles(), result.camera,
              image_size.x(), image_size.y());
          photometric_result = face_recon::FitPhotometricAppearance(
              *image_path, model, result.vertices, result.camera,
              *rasterization, photometric_options, output_dir);
        } else {
          std::cerr << "[WARN] Dense photometric refinement made no safe "
                       "improvement; keeping the landmark-based expression.\n";
        }
      }
      fitted_colors =
          photometric_result->fitted_vertex_albedo.size() ==
                  result.vertices.size()
              ? photometric_result->fitted_vertex_albedo
              : model.color().mean;
      std::cout << "[INFO] Fitting dense per-vertex RGB texture...\n";
      const face_recon::TextureFittingResult texture_result =
          face_recon::FitDenseVertexColors(
              *image_path, model.triangles(), *rasterization, fitted_colors,
              &landmarks, texture_options, output_dir);
      if (!texture_result.usable ||
          (save_diagnostics &&
           !face_recon::SaveTextureFittingReport(
               texture_result, texture_report_path.string()))) {
        std::cerr << "[ERROR] Dense RGB texture fitting did not improve the "
                     "rendered image error.\n";
        return 1;
      }
      fitted_colors = texture_result.vertex_colors;
      fitted_colors_pointer = &fitted_colors;
    }
    if (!face_recon::SaveMeshToOff(model, result.vertices, mesh_path.string()) ||
        !face_recon::SaveMeshToPly(model, result.vertices,
                                   colored_mesh_path.string(),
                                   fitted_colors_pointer) ||
        !face_recon::SaveFittingReport(result, report_path.string())) {
      return 1;
    }
    if (save_diagnostics) {
      const Eigen::VectorXd aligned_vertices =
          face_recon::ApplyCameraRotation(result.vertices, result.camera);
      if (!face_recon::SaveMeshToPly(
              model, aligned_vertices, aligned_mesh_path.string(),
              fitted_colors_pointer) ||
          !face_recon::SaveReprojectionsToCsv(
              result, reprojection_path.string())) {
        return 1;
      }
    }
    if (save_diagnostics && photometric_result.has_value() &&
        (!face_recon::SaveMeshToPly(
             model, result.vertices, intrinsic_albedo_mesh_path.string(),
             &photometric_result->fitted_vertex_albedo) ||
         !face_recon::SavePhotometricReport(
             *photometric_result, photometric_report_path.string()))) {
      return 1;
    }
    if (save_diagnostics && image_path.has_value() &&
        !face_recon::SaveReprojectionOverlay(
            *image_path, result, overlay_path.string())) {
      return 1;
    }
    if (save_diagnostics && rasterization.has_value() &&
        (!face_recon::SaveRasterDepthImage(
             *rasterization, raster_depth_path.string()) ||
         !face_recon::SaveVisibilityImage(
             *rasterization, visibility_path.string()))) {
      return 1;
    }
    std::cout << "[SUCCESS] Personalized reconstruction written to "
              << mesh_path << "\n";
  } else if (!check_bfm) {
    std::cout << "[INFO] Model loaded successfully. Pass --landmarks <csv> to fit a face "
                 "or --check-bfm to inspect the model.\n";
  }

  return 0;
}
