// Execution entry point for the 3D Face Reconstruction Pipeline.
// This binary handles command-line argument parsing, loads the statistical
// Basel Face Model, and orchestrates the facial alignment optimization loops.

#include "face_recon/bfm_model.h"
#include "face_recon/fitting.h"
#include "face_recon/image_fitting.h"
#include "face_recon/mesh_export.h"
#include "face_recon/rasterizer.h"
#include "face_reconstruction/landmarks.hpp"

#include <CLI/CLI.hpp>
#include <filesystem>
#include <iostream>
#include <optional>
#include <string>

int main(int argc, char* argv[]) {
  // Instantiate the App parser framework.
  CLI::App app{"TUM 3D Scanning and Motion Capture: 3D Face Reconstruction Optimization Loop Pipeline"};

  // Set up runtime parameters with safe defaults.
  std::string model_path = "data/model2019_face12.h5";
  std::string output_dir = "results";
  std::string correspondence_path = "data/bfm_mediapipe_correspondence.csv";
  std::optional<std::string> output_name;
  std::optional<std::string> landmark_path;
  std::optional<std::string> image_path;
  bool check_bfm = false;
  bool verbose_optimization = false;
  face_recon::FittingOptions fitting_options;

  // Define the available CLI flags and options.
  app.add_option("-m,--model", model_path, "Path to the Basel Face Model HDF5 asset container")->check(CLI::ExistingFile);
  app.add_option("-o,--output", output_dir, "Directory to save the reconstruction results");
  app.add_option("--output-name", output_name,
                 "Use compact filenames for a dedicated per-image output directory");
  app.add_flag("-c,--check-bfm", check_bfm, "Run structural loading checks and output comprehensive database dumps");
  app.add_option("-l,--landmarks", landmark_path,
                 "MediaPipe landmark CSV to fit; generated by scripts/detect_landmarks.py")
      ->check(CLI::ExistingFile);
  app.add_option("-i,--image", image_path,
                 "Original face image; enables photo colors and reprojection overlay")
      ->check(CLI::ExistingFile);
  app.add_option("--correspondences", correspondence_path,
                 "MediaPipe-to-BFM correspondence CSV")
      ->check(CLI::ExistingFile);
  app.add_option("--shape-components", fitting_options.num_shape_coefficients,
                 "Number of BFM identity coefficients to optimize");
  app.add_option("--expression-components", fitting_options.num_expression_coefficients,
                 "Number of BFM expression coefficients to optimize");
  app.add_option("--shape-regularization", fitting_options.shape_regularization,
                 "Weight of the identity PCA prior");
  app.add_option("--expression-regularization",
                 fitting_options.expression_regularization,
                 "Weight of the expression PCA prior");
  app.add_option("--landmark-weight", fitting_options.landmark_weight,
                 "Weight of the sparse landmark reprojection term");
  app.add_option("--contour-weight", fitting_options.contour_weight,
                 "Weight of the dynamic face contour term");
  app.add_option("--outlier-threshold", fitting_options.outlier_threshold,
                 "Maximum normalized residual before rejecting a semantic landmark");
  app.add_option("--contour-refinements", fitting_options.contour_refinement_steps,
                 "Number of dynamic contour reassignment steps");
  app.add_flag("-v,--verbose-optimization", verbose_optimization,
               "Print Ceres iteration progress");

  // Execute the parse routine safely
  try {
    app.parse(argc, argv);
  } catch (const CLI::ParseError& e) {
    // Print the correct usage information and exit with the corresponding exit code on wrong input.
    return app.exit(e);
  }

  if (fitting_options.num_shape_coefficients <= 0 ||
      fitting_options.num_expression_coefficients <= 0) {
    std::cerr << "[ERROR] Component counts must be positive.\n";
    return 1;
  }
  if (fitting_options.landmark_weight <= 0.0 ||
      fitting_options.contour_weight <= 0.0 ||
      fitting_options.shape_regularization < 0.0 ||
      fitting_options.expression_regularization < 0.0 ||
      fitting_options.outlier_threshold <= 0.0 ||
      fitting_options.contour_refinement_steps <= 0) {
    std::cerr << "[ERROR] Fitting weights, outlier threshold, and contour "
                 "refinement count must be valid positive values; "
                 "regularization may be zero.\n";
    return 1;
  }

  // Run the core execution pipeline.
  std::cout << "[INFO] Initializing Face Reconstruction Pipeline...\n";
  face_recon::BfmModel model;
  if (!model.LoadFromH5(model_path)) {
    std::cerr << "[ERROR] Failed to configure internal face model architecture from path: " << model_path << "\n";
    return 1;
  }

  // Ensure the output directory exists
  std::filesystem::create_directories(output_dir);

  // Orchestrate pipeline behavior based on runtime flags.
  if (check_bfm) {
    std::cout << "[INFO] Check BFM requested. Exporting validation logs and summaries...\n";
    
    // Output metrics to verify structural integrity.
    model.PrintModelSummary();

    // Generate static 3D face representations.
    model.SaveMeanMeshToPly(output_dir + "/bfm_mean_face.ply", false);
    model.SaveMeanMeshToPly(output_dir + "/bfm_mean_face_with_landmarks.ply", true);
    model.SaveLandmarksToTxt(output_dir + "/bfm_landmarks.txt");
  }

  if (landmark_path.has_value()) {
    fitting_options.verbose = verbose_optimization;
    std::cout << "[INFO] Loading sparse landmark observations...\n";
    const auto landmarks =
        face_reconstruction::load_landmarks_csv(*landmark_path);
    const auto correspondences =
        face_reconstruction::load_bfm_mediapipe_correspondences(correspondence_path);

    std::cout << "[INFO] Fitting camera, identity, and expression parameters...\n";
    const face_recon::FittingResult result =
        face_recon::FitBfmToLandmarks(model, landmarks, correspondences,
                                      fitting_options);
    std::cout << result.solver_summary << "\n";
    std::cout << "[RESULT] Landmark RMSE: " << result.initial_rmse
              << " -> " << result.final_rmse << " (normalized image units)\n";

    const bool compact_output = output_name.has_value();
    const std::string stem = compact_output
                                 ? *output_name
                                 : std::filesystem::path(*landmark_path).stem().string();
    const std::filesystem::path mesh_path =
        std::filesystem::path(output_dir) /
        (compact_output ? stem + ".off" : stem + "_fitted.off");
    const std::filesystem::path colored_mesh_path =
        std::filesystem::path(output_dir) /
        (compact_output ? stem + ".ply" : stem + "_fitted.ply");
    const std::filesystem::path aligned_mesh_path =
        std::filesystem::path(output_dir) /
        (compact_output ? stem + "_aligned.ply" : stem + "_fitted_aligned.ply");
    const std::filesystem::path report_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "fitting.txt" : stem + "_fitting.txt");
    const std::filesystem::path reprojection_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "reprojections.csv" : stem + "_reprojections.csv");
    const std::filesystem::path overlay_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "overlay.png" : stem + "_fitting_overlay.png");
    const std::filesystem::path raster_depth_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "raster_depth.png" : stem + "_raster_depth.png");
    const std::filesystem::path visibility_path =
        std::filesystem::path(output_dir) /
        (compact_output ? "visibility.png" : stem + "_visibility.png");

    if (!result.usable) {
      std::cerr << "[ERROR] Ceres did not produce a usable fitting result.\n";
      return 1;
    }
    Eigen::VectorXd fitted_colors;
    const Eigen::VectorXd* fitted_colors_pointer = nullptr;
    std::optional<face_recon::RasterizationResult> rasterization;
    if (image_path.has_value()) {
      const Eigen::Vector2i image_size =
          face_recon::ReadImageSize(*image_path);
      rasterization = face_recon::RasterizeMesh(
          result.vertices, model.triangles(), result.camera,
          image_size.x(), image_size.y());
      fitted_colors = face_recon::SampleVisibleVertexColorsFromImage(
          *image_path, result.vertices, *rasterization, model.color().mean);
      fitted_colors_pointer = &fitted_colors;
    }
    const Eigen::VectorXd aligned_vertices =
        face_recon::ApplyCameraRotation(result.vertices, result.camera);

    if (!face_recon::SaveMeshToOff(model, result.vertices, mesh_path.string()) ||
        !face_recon::SaveMeshToPly(model, result.vertices,
                                   colored_mesh_path.string(),
                                   fitted_colors_pointer) ||
        !face_recon::SaveMeshToPly(model, aligned_vertices,
                                   aligned_mesh_path.string(),
                                   fitted_colors_pointer) ||
        !face_recon::SaveFittingReport(result, report_path.string()) ||
        !face_recon::SaveReprojectionsToCsv(result, reprojection_path.string())) {
      return 1;
    }
    if (image_path.has_value() &&
        !face_recon::SaveReprojectionOverlay(
            *image_path, result, overlay_path.string())) {
      return 1;
    }
    if (rasterization.has_value() &&
        (!face_recon::SaveRasterDepthImage(
             *rasterization, raster_depth_path.string()) ||
         !face_recon::SaveVisibilityImage(
             *rasterization, visibility_path.string()))) {
      return 1;
    }
    std::cout << "[SUCCESS] Personalized reconstruction written to "
              << mesh_path << "\n";
  } else if (!check_bfm) {
    std::cout << "[INFO] Model loaded successfully. Pass --landmarks <csv> to fit a face "
                 "or --check-bfm to inspect the model.\n";
  }

  return 0;
}
